## Operaciones con Listas Python vs Lista en Numpy


#### Operacion Suma Listas Python 

In [19]:
list1 = [1,2,3] #Definimos una variable de nombre list y asignamos una coleccion de valores
print(list1)
print("El tipo de datos es:  {0}".format(type(list1)))# Imprimimos el tipo de dato de la variable list con la funcion type

[1, 2, 3]
El tipo de datos es  <class 'list'>


In [15]:
list2 = [4,5,6] #Definimos una variable de nombre list2 y asignamos una coleccion de valores
print(list2)
print("El tipo de datos es:  {0}".format(type(list2)))

[4, 5, 6]
El tipo de datos es  <class 'list'>


In [14]:
listsuma= list1 + list2 #Realizamos la operacion suma entre 2 listas
print(listsuma) #El resultado nos da la concatenación de los elementos de las 2 listas

[1, 2, 3, 4, 5, 6]


#### Operacion Suma Listas con Libreria Numpy 

Con la librería Numpy podemos hacer operaciones con matrices unidimensionales(listas), 2 dimensiones, etc.  
Es más óptimo y rápido que las listas de Python, el comportamiento de las operaciones son distintas a las listas de Python.

In [20]:
import numpy as np #Importamos la libreria numpy 
list1= np.array([1,2,3]) #Definimos una lista numpy
print(list1)
print("El tipo de datos es:  {0}".format(type(list1)))# Imprimimos el tipo de dato de la variable list con la funcion type
#Observamos que el tipo de datos es numpy.ndarray , ndarray hace referencia a multidimensional

[1 2 3]
El tipo de datos es  <class 'numpy.ndarray'>


In [22]:
list2= np.array([4,5,6]) #Definimos una lista numpy
print(list2)
print("El tipo de datos es  {0}".format(type(list2)))

[4 5 6]
El tipo de datos es  <class 'numpy.ndarray'>


In [24]:
listsuma= list1 + list2
print(list1 + list2)
print("El tipo de datos es  {0}".format(type(listsuma)))

[5 7 9]
El tipo de datos es  <class 'numpy.ndarray'>


Vemos que la operacion suma es distinta a la lista de Python, esta forma de trabajar de Numpy esta orientado a que las operaciones sean las mismas que las matemáticas de matrices.